#CONFIGURACIÓN DE LA BASE DE DATOS + COMPROBAR CONEXIÓN

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: #Put a password here

#CONFIGURACIÓN JPA
  jpa.hibernate.ddl_auto: create
